mysu-objs := core/init.o

mysu-objs += feature/kernel_umount.o
mysu-objs += feature/sulog.o
mysu-objs += feature/sucompat.o

mysu-objs += hook/lsm_hook.o
mysu-objs += hook/setuid_hook.o
mysu-objs += hook/syscall_event_bridge.o
mysu-objs += hook/syscall_hook_manager.o
mysu-objs += hook/tp_marker.o
ifeq ($(CONFIG_ARM64),y)
mysu-objs += hook/arm64/patch_memory.o
mysu-objs += hook/arm64/syscall_hook.o
else ifeq ($(CONFIG_X86_64),y)
mysu-objs += hook/x86_64/patch_memory.o
mysu-objs += hook/x86_64/syscall_hook.o
endif

mysu-objs += infra/file_wrapper.o
mysu-objs += infra/event_queue.o
mysu-objs += infra/seccomp_cache.o
mysu-objs += infra/su_mount_ns.o
mysu-objs += infra/symbol_resolver.o

ifneq ($(CONFIG_MYSU_DISABLE_MANAGER),y)
mysu-objs += manager/apk_sign.o
mysu-objs += manager/pkg_observer.o
mysu-objs += manager/throne_tracker.o
endif

mysu-objs += policy/allowlist.o
mysu-objs += policy/app_profile.o
mysu-objs += policy/feature.o

mysu-objs += runtime/boot_event.o
mysu-objs += runtime/mysud_integration.o

mysu-objs += selinux/selinux.o
mysu-objs += selinux/rules.o
mysu-objs += selinux/sepolicy.o

mysu-objs += sulog/event.o
mysu-objs += sulog/fd.o

mysu-objs += supercall/dispatch.o
mysu-objs += supercall/perm.o
mysu-objs += supercall/supercall.o

mysu-objs += feature/adb_root.o

mysu-objs += feature/selinux_hide.o

ifdef KBUILD_EXTMOD
ifeq ($(CONFIG_MYSU_DISABLE_MANAGER),y)
ccflags-y += -DCONFIG_MYSU_DISABLE_MANAGER=1
endif
ifeq ($(CONFIG_MYSU_DISABLE_POLICY),y)
ccflags-y += -DCONFIG_MYSU_DISABLE_POLICY=1
endif
ifeq ($(CONFIG_MYSU_DEBUG),y)
ccflags-y += -DCONFIG_MYSU_DEBUG=1
endif
ifeq ($(CONFIG_MYSU_X86_PATCH_SYSCALL_DISPATCHER),y)
ccflags-y += -DCONFIG_MYSU_X86_PATCH_SYSCALL_DISPATCHER=1
endif
endif

ccflags-y += -I$(srctree)/security/selinux -I$(srctree)/security/selinux/include
ccflags-y += -I$(objtree)/security/selinux -include $(srctree)/include/uapi/asm-generic/errno.h

ifeq ($(filter /%,$(src)),)
MYSU_KERNEL_DIR := $(srctree)/$(src)
else
MYSU_KERNEL_DIR := $(src)
endif

ccflags-y += -I$(MYSU_KERNEL_DIR) -I$(MYSU_KERNEL_DIR)/include

obj-$(CONFIG_MYSU) += mysu.o
obj-$(CONFIG_MYSU) += mysu.o

MDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

# Workaround bazel
# https://github.com/kelexine/MySU/pull/316#issuecomment-1479043219
GIT := $(shell PATH="$$PATH":/usr/bin:/usr/local/bin which git)
ifneq ($(GIT),)
# Check if this is a git repository
# Try to detect Git repo intelligently
GIT_ROOT := $(shell cd $(MDIR) && $(GIT) rev-parse --show-toplevel 2>/dev/null)
ifneq ($(GIT_ROOT),)
KERNEL_GIT_ROOT := $(shell cd $(srctree) && $(GIT) rev-parse --show-toplevel 2>/dev/null)
ifneq ($(GIT_ROOT),$(KERNEL_GIT_ROOT))
# Only set version if it's a different repo from kernel
$(shell cd $(GIT_ROOT) && [ -f .git/shallow ] && $(GIT) fetch --unshallow 2>/dev/null || true)
MYSU_GIT_VERSION := $(shell cd $(GIT_ROOT) && $(GIT) rev-list --count HEAD 2>/dev/null)
MYSU_GIT_VERSION_VALID := 1
$(info -- MySU: Git repo detected at $(GIT_ROOT))
endif
endif
else
$(warning -- MySU: Git not detected, make sure git is installed in your PATH!)
endif


# Calculate version if git version is available
ifdef MYSU_GIT_VERSION_VALID
# mysu_version: major * 10000 + git version + 200 for historical reasons
$(eval MYSU_VERSION=$(shell expr 30000 + $(MYSU_GIT_VERSION)))
$(info -- MySU version: $(MYSU_VERSION))
ccflags-y += -DMYSU_VERSION=$(MYSU_VERSION)
else
# If there is no .git directory, use default version
$(warning "MYSU_GIT_VERSION not defined! It is better to make MySU a git repository!")
ccflags-y += -DMYSU_VERSION=16
endif

MYSU_NEW_DCACHE_FLUSH := $(shell grep -q __flush_dcache_area $(srctree)/arch/arm64/include/asm/cacheflush.h ; echo $$?)
$(info -- MYSU_NEW_DCACHE_FLUSH: $(MYSU_NEW_DCACHE_FLUSH))


ifndef MYSU_EXPECTED_SIZE
MYSU_EXPECTED_SIZE := 0x033b
endif

ifndef MYSU_EXPECTED_HASH
MYSU_EXPECTED_HASH := c371061b19d8c7d7d6133c6a9bafe198fa944e50c1b31c9d8daa8d7f1fc2d2d6
endif

ifndef MYSU_MANAGER_PACKAGE
MYSU_MANAGER_PACKAGE := dev.kelexine.mysu
endif

ifdef MYSU_MANAGER_PACKAGE
ccflags-y += -DMYSU_MANAGER_PACKAGE=\"$(MYSU_MANAGER_PACKAGE)\"
$(info -- MySU Manager package name: $(MYSU_MANAGER_PACKAGE))
endif

$(info -- MySU Manager signature size: $(MYSU_EXPECTED_SIZE))
$(info -- MySU Manager signature hash: $(MYSU_EXPECTED_HASH))

ccflags-y += -DEXPECTED_SIZE=$(MYSU_EXPECTED_SIZE)
ccflags-y += -DEXPECTED_HASH=\"$(MYSU_EXPECTED_HASH)\"

ifdef MYSU_EXPECTED_SIZE2
ifndef MYSU_EXPECTED_HASH2
$(error MYSU_EXPECTED_HASH2 must be set when MYSU_EXPECTED_SIZE2 is set)
endif
ccflags-y += -DEXPECTED_SIZE2=$(MYSU_EXPECTED_SIZE2)
ccflags-y += -DEXPECTED_HASH2=\"$(MYSU_EXPECTED_HASH2)\"
$(info -- MySU Manager signature size2: $(MYSU_EXPECTED_SIZE2))
$(info -- MySU Manager signature hash2: $(MYSU_EXPECTED_HASH2))
endif

ccflags-y += -DMYSU_NEW_DCACHE_FLUSH=$(MYSU_NEW_DCACHE_FLUSH)

ccflags-y += -Wno-strict-prototypes -Wno-int-conversion -Wno-gcc-compat -Wno-missing-prototypes
ccflags-y += -Wno-declaration-after-statement -Wno-unused-function

# Keep a new line here!! Because someone may append config
