#ifndef __MYSU_UAPI_FEATURE_H
#define __MYSU_UAPI_FEATURE_H

enum mysu_feature_id {
    MYSU_FEATURE_SU_COMPAT = 0,
    MYSU_FEATURE_KERNEL_UMOUNT = 1,
    MYSU_FEATURE_SULOG = 2,
    MYSU_FEATURE_ADB_ROOT = 3,
    MYSU_FEATURE_SELINUX_HIDE = 4,

    MYSU_FEATURE_MAX
};

/* Compatibility aliases */
#define mysu_feature_id mysu_feature_id
#define MYSU_FEATURE_SU_COMPAT MYSU_FEATURE_SU_COMPAT
#define MYSU_FEATURE_KERNEL_UMOUNT MYSU_FEATURE_KERNEL_UMOUNT
#define MYSU_FEATURE_SULOG MYSU_FEATURE_SULOG
#define MYSU_FEATURE_ADB_ROOT MYSU_FEATURE_ADB_ROOT
#define MYSU_FEATURE_SELINUX_HIDE MYSU_FEATURE_SELINUX_HIDE
#define MYSU_FEATURE_MAX MYSU_FEATURE_MAX

#endif
